### ISSUE TITLE
hitting deadlock with latest published version

### ISSUE THREAD

**Issue by dwrensha** [withoutboats/romio#103]
Can we get a new release on crates.io?

I'm seeing some deadlocks occasionally happen in some of my tests with romio version `0.3.0-alpha.9`: https://github.com/capnproto/capnproto-rust/blob/15163beb08b3efc31ec94f0fd1b704a60489726f/capnp-rpc/test/Cargo.toml

The deadlock does not happen with the latest git version of romio.

This is the commit that made the deadlock go away: https://github.com/withoutboats/romio/commit/2caa8d6716fea2400d0586dee74fe0c9e0cc787b

My guess is that the `parking_lot` update is responsible. That crate's changelog does indicate that there have been some relevant-looking bugfixes between `0.7.1` and `0.9.0`: https://github.com/Amanieu/parking_lot/blob/master/CHANGELOG.md

**Comment by yoshuawuyts** [comment]
@dwrensha thanks for reporting! -- we've just released romio `0.3.0-alpha.10` as per #104.

However, please note that this crate is currently not actively maintained. Instead we recommend checking out the successor to this crate: [`async-std`](https://github.com/async-rs/async-std/), which contains a complete runtime written from the ground up.

**Comment by dwrensha** [comment]
Thanks!

> However, please note that this crate is currently not actively maintained. Instead we recommend checking out the successor to this crate: async-std, which contains a complete runtime written from the ground up.

It would be good to mention this in romio's readme.
