### ISSUE TITLE
build & link to docs

### ISSUE THREAD

**Issue by yoshuawuyts** [withoutboats/romio#44]
Currently https://docs.rs/romio is coming up empty, despite being published yet. Having docs available would probably be great. For completion, I think we should:

- [ ] figure out why docs.rs isn't building
- [ ] add a link to docs.rs from Cargo.toml
- [ ]  add a link to docs.rs from the README
- [ ] add a link to crates.io from the README

## Example README badges:

__rendered__

[![crates.io version](https://img.shields.io/crates/v/romio.svg?style=flat-square)](https://crates.io/crates/romio) [![docs.rs](https://img.shields.io/badge/docs-latest-blue.svg?style=flat-square)](https://docs.rs/romio)

__inline source__

```md
[![crates.io version](https://img.shields.io/crates/v/romio.svg?style=flat-square)](https://crates.io/crates/romio) [![docs.rs](https://img.shields.io/badge/docs-latest-blue.svg?style=flat-square)](https://docs.rs/romio)
```

__neat source__

```md
[![crates.io version][1]][2] [![docs.rs docs][7]][8]

[1]: https://img.shields.io/crates/v/romio.svg?style=flat-square
[2]: https://crates.io/crates/romio
[7]: https://img.shields.io/badge/docs-latest-blue.svg?style=flat-square
[8]: https://docs.rs/romio
```

**Comment by withoutboats** [comment]
docs.rs probably isn't building because we depend on a very recent nightly. docs.rs only updates its nightlys occasionally, and has lately been having some real problems with that for infrastructural reasons I don't know.

We should probably host our own docs on GitHub pages.

**Comment by yoshuawuyts** [comment]
@withoutboats sounds good! Just published docs to the [gh-pages branch](https://github.com/withoutboats/romio/tree/gh-pages). Just needs a setting to be toggled in order to enable it (which I don't have access to).

Once published the docs should be available from: https://withoutboats.github.io/romio/romio/index.html (it would indeed be `romio/romio`).

Perhaps one step up we could have is enable gh-pages to be built from Travis. I ran my [crossgen](https://github.com/yoshuawuyts/crossgen) command to obtain an encrypted token for use with this repo:

```txt
"RiEo7/jAXW3AdhX3eF7N+rOEcTxKecB5lnwlIiX110z10dVJgMoLisRRFF9NgyAqNIrrIkzDnu1YDqT8OyMU1YXPRlurPDNI0TL8lF0zAieaECSEe6mwXbAAwlmbmWTmkEfak4EWs1+4bD6XfZAsYwR3qsmJ6dejhxztdAm06EsX2UsGCdaaczPATd5NlnXS0YGIxu9cGL74hlVLUuhd1qbjvNiU2GPdaJ9THE2rskJlA6Wt0nQoYa9Glml4YbMD+LJI+vEs2EoMIwJoQ1/pBxicgY4WHARiv+V5hOgD7MowC0Ebra2NLtTl3E3TJc44llC8dmxVsPSUahx/p+UnxqEw3QV0Q/OzGSGQE5ggC8vQuDueTiHyFnVXG3r3YzLrwZrc4cZcVfL7plWlGxaNHU9ulKYjg+qkFI10MMUHQ7iStYBfEe7C7ovIUuEwhATd/j4VAUq7SWIsLoBJMxa/HHd0ahE4aE3WmcKVljhGPliSxg1ZR6l3LuSxKZ7tLwoKDC6l26I3w6A+msrbIdyVwwNi8b2NQsBlCCAo9klMAAi4jiOcRqBVaC/ZNQtRTFqKu9IcUkEANs55ce8P54yXWcNY0HoW9skkYPPNvIULxoBSU7aV/AWkPhWidZEoxZ9Jz2ZATt99BnSVCzFFOrtaPixwyiF9WXnhAzt6D4zy2u4="
```
Instructions on how to set up travis for building gh-pages can be found here: https://docs.travis-ci.com/user/deployment/pages/

**Comment by withoutboats** [comment]
I figured out the problem with building our own docs: it was that I had an old pages repo withoutboats.github.io. Now that I've renamed that repo, our docs build:

https://withoutboats.github.io/romio/romio/

**Comment by withoutboats** [comment]
Haven't investigated but travis docs deploy from master is failing
