### ISSUE TITLE
`reactor::PollEvented` should be public

### ISSUE THREAD

**Issue by nikonthethird** [withoutboats/romio#52]
Currently, the `reactor` module is private in `lib.rs`, it is therefore not possible to pass a custom `Evented` implementation into Romio using `PollEvented`.

`PollEvented` should be publicly accessible, like it is in Tokio.

**Comment by yoshuawuyts** [comment]
What would be a reason to pass a custom Evented impl?

**Comment by nikonthethird** [comment]
I am implementing GPIO access using async/await. From the linux kernel, I get back [a raw file descriptor](https://github.com/torvalds/linux/blob/master/include/uapi/linux/gpio.h#L134), that I wrap into an [`EventedFd`](https://carllerche.github.io/mio/mio/unix/struct.EventedFd.html).

That's where I'm stuck, because I can't finish my async implementation of "wait for this GPIO pin to change" without somehow getting it into the Romio event loop, right?

That's what you would use `PollEvented` in Tokio for to the best of my understanding. And this type is not accessible in Romio.

**Comment by kpp** [comment]
How would you implement it with public `reactor::PollEvented`? Let's assume it is public.

**Comment by nikonthethird** [comment]
I was looking at the implementation of [`tokio-file`](https://github.com/asomers/tokio-file/blob/master/src/file.rs#L122), which uses mio's `PollEvented2`. The idea is:

* The connected GPIO pin implements `Evented` by just creating a [`EventedFd`](https://carllerche.github.io/mio/mio/unix/struct.EventedFd.html) like in the example there.
* When `wait_for_pin_async` is called, it constructs a new `PollEvented` with the connected pin (that implements `Evented`), and wraps it inside a new struct.
* This struct implements `Future` like in the `tokio-file` case but simpler, calling `poll_read` with the waker and reading the result.

**Comment by withoutboats** [comment]
I think this type should be public, since its an essential building block for building new async IO primitives that work on romio's reactor. Not sure what the module hierarchy should be, some new module that implies that its contents (`PollEvented`) are for low level use cases. Idk, `raw` maybe?

**Comment by withoutboats** [comment]
I think this type should be public, since its an essential building block for building new async IO primitives that work on romio's reactor. Not sure what the module hierarchy should be, some new module that implies that its contents (`PollEvented`) are for low level use cases. Idk, `raw` maybe?

**Comment by marcelbuesing** [comment]
I ported a version of  `socketcan-tokio` to [socketcan-romio](https://github.com/marcelbuesing/socketcan-rs/tree/dev/socketcan-romio) all I needed is a [fork](https://github.com/marcelbuesing/romio/commit/5fc61da10411d578ecc6c4cd862e1471d510c96c) with a public `PollEvented`. So it'd be great to have this for this too.

**Comment by withoutboats** [comment]
All we really need is a name for the module it would go under which would contain these advanced, building block style components.

**Comment by nikonthethird** [comment]
I have the following ideas:

* `infra`(`structure`)
* `core`
* `internal`

**Comment by kpp** [comment]
raw?

**Comment by marcelbuesing** [comment]
raw or core sound good to me

**Comment by withoutboats** [comment]
I would love to see and happily merge a PR exporting `PollEvented` under a `raw` module ;)

**Comment by withoutboats** [comment]
Probably the best thing would be to just move `PollEvented` to a new public module called `raw`, rather than some sort of export, since other things in `reactor` don't depend on it.

**Comment by yoshuawuyts** [comment]
Reactor PollEvented is now public! :tada:
