### ISSUE TITLE
nightly std library change breaks romio

### ISSUE THREAD

**Issue by lijinpei** [withoutboats/romio#65]
As of rustc 1.34.0-nightly (146aa60f3 2019-02-18), Wake, local_waker, local_waker_from_nonlocal is removed from std, which breaks romio's master branch.

**Comment by yoshuawuyts** [comment]
@lijinpei thanks for the heads up! -- we should fix this ASAP.

**Comment by yoshuawuyts** [comment]
Looks like this is blocked by a new release of `futures-preview`. Waiting on `0.3.0-alpha.13`.

**Comment by withoutboats** [comment]
Published version `0.3.0-alpha.2` which fixes this issue!
