### ISSUE TITLE
Update to futures alpha 13

### ISSUE THREAD

**Issue by PvdBerg1998** [withoutboats/romio#70]
Currently Romio is unusable with weird missing trait implementation errors when combined with futures alpha 13.
Recently a PR got merged to update the source to use the last futures version, but Cargo.toml was forgotten.

**Comment by taiki-e** [comment]
Probably addressed in #69.

**Comment by kpp** [comment]
> Currently Romio is unusable with weird missing trait implementation errors when combined with futures alpha 13.

Which errors exactly do you get?

**Comment by PvdBerg1998** [comment]
I commented this on the last PR that got closed. I'm on mobile so please have a look there.

**Comment by PvdBerg1998** [comment]
@taiki-e I see, I'll close the issue :+1:

**Comment by withoutboats** [comment]
Published version `0.3.0-alpha.2` which fixes this issue!
