### ISSUE TITLE
Update to futures alpha 15

### ISSUE THREAD

**Issue by SiMaCuo** [withoutboats/romio#88]
Today, I upgraded the related items to the following versions:
        Romio-0.3.0-alpha.6
        Futures alpha 15
        Rustc 1.36.0-nightly (d595b1135 2019-05-10)
Get some compilation errors that I can't solve myself:
![image](https://user-images.githubusercontent.com/16982243/57564280-0a0af380-73dc-11e9-9a04-87049e2211d5.png)
I am grateful for any suggestions.

**Comment by taiki-e** [comment]
Fixed in #87 (It was necessary to update to 0.3.0-alpha.16 to fix this problem).
